---
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Max: 200
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Max: 7
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'
    - '**/Vagrantfile'
Style/TrivialAccessors:
  ExactNameMatch: true
