---
AllCops:
  Include:
    - Rakefile
  Exclude:
    - vendor/**/*
ClassLength:
  Max: 200
Documentation:
  Enabled: false
EmptyLinesAroundBody:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 25
ParameterLists:
  Max: 7
TrivialAccessors:
  ExactNameMatch: true
