language: ruby
rvm:
- 2.1.5
notifications:
  slack:
    secure: V8CqQIkTCcpOOb/COLIRxKe71X0jU1k5S+dhzREenJ6tvv3fGHprcsL8A8uYdLO89TC4Y/kXRxo71sIew2afzpB4xTenxGd0tjaCbXqOS2ulOmGp3swGseEi3CDUjZB7wUzL8mOoT/NmmKxe9PfVV1WIo7FQIfHlZA4Q2HMSgLw=
  webhooks:
    urls:
    - http://build-monitor.cfapps.io/projects/BLDR/webhook
    on_start: true
env:
  global:
    secure: ZKHsD1wEfqZaYRvXjTe0lN277mrOmJF8hCIA+0BtAWSbRN3gd3PirAdQ5w9SVSTvHoNjdO/ZOMObG7IZP8v21XwgmFGg1JEp7sW2Lj5M2TwwXuWyGiLlkEZEKBYSMLKTGOtXK8FoEmM8Ti39MRh40DkDPrHME/TMDK03ONIUJN4= #CODECLIMATE_REPO_TOKEN
