---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-buildpack-dependency-builder
    tag: latest

inputs:
- name: java-buildpack-dependency-builder

run:
  path: java-buildpack-dependency-builder/gem-fire-security.sh

params:
  DOWNLOAD_VERSION: 8.2.1
  UPLOAD_VERSION:   8.2.1

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  CLOUDFRONT_DISTRIBUTION_IDS:
  S3_BUCKET:
