---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-buildpack-dependency-builder
    tag: latest

inputs:
- name: java-buildpack-dependency-builder

run:
  path: java-buildpack-dependency-builder/tomee-resource-configuration.sh

params:
  DOWNLOAD_VERSION: 1.0.0.RELEASE
  UPLOAD_VERSION:   1.0.0_RELEASE

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  CLOUDFRONT_DISTRIBUTION_IDS:
  S3_BUCKET:
