---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

inputs:
- name: java-buildpack-dependency-builder

outputs:
- name: docker-image

run:
  path: java-buildpack-dependency-builder/maven-central-resource/ci/build.sh
